#!/usr/bin/env bash
set -euo pipefail

: "${CAPABILITY_NAME:?CAPABILITY_NAME is required}"
: "${CAPABILITY_DIR:?CAPABILITY_DIR is required}"

source ~/.bash_profile

COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$COMMON_DIR/../../../.." && pwd)"
HUOSHAN_DIR="$(cd "$COMMON_DIR/../.." && pwd)"

if [ -f "$HUOSHAN_DIR/.env" ]; then
    source "$HUOSHAN_DIR/.env"
fi

: "${HUOSHAN_CR_USERNAME:?HUOSHAN_CR_USERNAME is required}"
: "${HUOSHAN_CR_PASSWORD:?HUOSHAN_CR_PASSWORD is required}"
: "${CAPABILITY_APIG_GATEWAY_ID:?CAPABILITY_APIG_GATEWAY_ID is required}"

CAPABILITY_RUN_SCRIPT="${CAPABILITY_RUN_SCRIPT:-deploy_script/huoshan/capabilities/$CAPABILITY_NAME/run.sh}"
CAPABILITY_BASE_IMAGE="${CAPABILITY_BASE_IMAGE:-dcc-cloud2-cn-beijing.cr.volces.com/dcc-cloud/zou-capability-base:dev}"
GIT_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || true)"
DEFAULT_IMAGE_TAG="$(date -u +%Y%m%d%H%M%S)${GIT_SHA:+-$GIT_SHA}"
DEFAULT_IMAGE_REPOSITORY="dcc-cloud2-cn-beijing.cr.volces.com/dcc-cloud/zou-capability-$CAPABILITY_NAME"
CAPABILITY_IMAGE_REPOSITORY="${CAPABILITY_IMAGE_REPOSITORY:-$DEFAULT_IMAGE_REPOSITORY}"
CAPABILITY_IMAGE_TAG="${CAPABILITY_IMAGE_TAG:-$DEFAULT_IMAGE_TAG}"
export CAPABILITY_IMAGE="${CAPABILITY_IMAGE:-$CAPABILITY_IMAGE_REPOSITORY:$CAPABILITY_IMAGE_TAG}"

if [ ! -f "$REPO_ROOT/$CAPABILITY_RUN_SCRIPT" ]; then
    echo "Missing capability run script: $CAPABILITY_RUN_SCRIPT" >&2
    exit 1
fi

export DB_HOST="${CAPABILITY_DB_HOST:-${DEV_DB_HOST:-${DB_HOST:-}}}"
export DB_PORT="${CAPABILITY_DB_PORT:-${DEV_DB_PORT:-${DB_PORT:-5432}}}"
export DB_DATABASE="${CAPABILITY_DB_DATABASE:-${DEV_DB_DATABASE:-${DB_DATABASE:-}}}"
export DB_USERNAME="${CAPABILITY_DB_USERNAME:-${DEV_DB_USERNAME:-${DB_USERNAME:-}}}"
export DB_PASSWORD="${CAPABILITY_DB_PASSWORD:-${DEV_DB_PASSWORD:-${DB_PASSWORD:-}}}"
export KV_HOST="${CAPABILITY_KV_HOST:-${DEV_KV_HOST:-${KV_HOST:-}}}"
export KV_PORT="${CAPABILITY_KV_PORT:-${DEV_KV_PORT:-${KV_PORT:-6379}}}"
export KV_USERNAME="${CAPABILITY_KV_USERNAME:-${DEV_KV_USERNAME:-${KV_USERNAME:-}}}"
export KV_PASSWORD="${CAPABILITY_KV_PASSWORD:-${DEV_KV_PASSWORD:-${KV_PASSWORD:-}}}"
export KV_CAPABILITY_JOBS_DB_INDEX="${CAPABILITY_KV_CAPABILITY_JOBS_DB_INDEX:-${DEV_KV_CAPABILITY_JOBS_DB_INDEX:-25}}"
export SECRET_KEY="${CAPABILITY_SECRET_KEY:-${DEV_SECRET_KEY:-${SECRET_KEY:-}}}"
export FAAS_CAPABILITY_TOKEN="${FAAS_CAPABILITY_TOKEN:-${CAPABILITY_SECRET_KEY:-${DEV_SECRET_KEY:-${SECRET_KEY:-}}}}"
export DOMAIN_NAME="${CAPABILITY_DOMAIN_NAME:-${DEV_DOMAIN_NAME:-${DOMAIN_NAME:-localhost}}}"
export DOMAIN_PROTOCOL="${CAPABILITY_DOMAIN_PROTOCOL:-${DEV_DOMAIN_PROTOCOL:-${DOMAIN_PROTOCOL:-https}}}"
export MAIL_ENABLED="${CAPABILITY_MAIL_ENABLED:-False}"
export FS_BACKEND="${CAPABILITY_FS_BACKEND:-${DEV_FS_BACKEND:-${FS_BACKEND:-s3}}}"
export FS_S3_REGION="${CAPABILITY_FS_S3_REGION:-${DEV_FS_S3_REGION:-${FS_S3_REGION:-oss-cn-beijing}}}"
export FS_S3_ENDPOINT="${CAPABILITY_FS_S3_ENDPOINT:-${DEV_FS_S3_ENDPOINT:-${FS_S3_ENDPOINT:-https://oss-cn-beijing.aliyuncs.com}}}"
export FS_S3_ACCESS_KEY="${CAPABILITY_FS_S3_ACCESS_KEY:-${DEV_FS_S3_ACCESS_KEY:-${FS_S3_ACCESS_KEY:-}}}"
export FS_S3_SECRET_KEY="${CAPABILITY_FS_S3_SECRET_KEY:-${DEV_FS_S3_SECRET_KEY:-${FS_S3_SECRET_KEY:-}}}"
export FS_BUCKET_PREFIX="${CAPABILITY_FS_BUCKET_PREFIX:-${DEV_FS_BUCKET_PREFIX:-dcc-kitsu-dev-}}"

echo "Deploying capability image: $CAPABILITY_IMAGE"

printf '%s' "$HUOSHAN_CR_PASSWORD" | docker login \
    --username="$HUOSHAN_CR_USERNAME" \
    --password-stdin \
    dcc-cloud2-cn-beijing.cr.volces.com

docker build \
    --platform linux/amd64 \
    --build-arg "CAPABILITY_BASE_IMAGE=$CAPABILITY_BASE_IMAGE" \
    --build-arg "CAPABILITY_RUN_SCRIPT=$CAPABILITY_RUN_SCRIPT" \
    -t "$CAPABILITY_IMAGE" \
    -f "$COMMON_DIR/Dockerfile" \
    "$REPO_ROOT"

docker push "$CAPABILITY_IMAGE"

cd "$CAPABILITY_DIR"
s deploy
