edition: 1.0.0
name: video_to_audio
# access 是当前应用所需要的密钥信息配置：
# 密钥配置可以参考：https://www.serverless-devs.com/serverless-devs/command/config
# 密钥使用顺序可以参考：https://www.serverless-devs.com/serverless-devs/tool#密钥使用顺序与规范
access: 'default'

vars: # 全局变量
  region: 'cn-hangzhou'
  service:
    name: video_to_audio-service
    description: 'hello world by serverless devs'
    internetAccess: true

services:
  video_to_audio:
    component: scf
    Provider: tencent
    Access: release
    actions: # 自定义执行逻辑，关于actions 的使用，可以参考：https://www.serverless-devs.com/serverless-devs/yaml#行为描述
      pre-deploy: # 在deploy之前运行
        - component: fc build --use-docker --dockerfile ../../Dockerfile # 要运行的组件，格式为【component: 组件名 命令 参数】（可以通过s cli registry search --type Component 获取组件列表）
    props:
      region: ${vars.region} # 关于变量的使用方法，可以参考：https://www.serverless-devs.com/serverless-devs/yaml#变量赋值
      service: ${vars.service}
      function:
        name: 'video_to_audio-func'
        Role: exRole
        description: 'hello world by serverless devs'
        caPort: 9000
        handler: index.handler
        diskSize: 10240
        timeout: 9000
        runtime: custom-container
        cpu: 8
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: 'ccr.ccs.tencentyun.com/dcc-cloud/video_to_audio:0.0.1'
          accelerationInfo:
            status: Preparing
          command: ''
        instanceConcurrency: 10
        memorySize: 32768
        asyncConfiguration: {}
        environmentVariables:
          KEYID: ${env(KEYID)}
          KEYSECRET: ${env(KEYSECRET)}
          OSS_ENDPOINT: oss-cn-hangzhou.aliyuncs.com
          CLOUD_PROVIDER: OSS
      triggers:
        - name: httpTrigger
          type: http
          qualifier: LATEST
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
